before_script:
  - curl -s -L https://github.com/Keats/gutenberg/releases/download/v0.3.1/gutenberg-v0.3.1-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
script:
  - gutenberg --config config.toml build
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: Oufj4oNvtFr98ny/dpoar4+ObCTjYGbh2smZ5EUMz4dL9qodCsg2+IIbcMwwWGGydAH5XjG4syEzeyxsquRlD0B0E75NTPzKUyqAZ8hom0wnyPDuwPcGOxOgYvPW7Dxo9kJO6kreyXZKmGg9rMOyEGKGyYcSJqk5EXHkFpuc79Jx+99A3zvarB+QAUvAADevTNYb5nFpUV3DCV1E5X3dVy0fNv7gyBU83GzrXAxlwfFXCwbf9PIEEhxSnyzD6EPt/EgUn9RLJyazwgY1uu1VsQ5/Q4hov3EiKRYtWpjAcgvLM1O4phTngXogQg+BYwXaSvaqSwh6FwlkXar2z47sqi3ej8it99v1NawCGP3Z233OeqdISKawhFjUwh1p6iuDy1hma1qGwLgCh0aapfgi09Obbp1XqhJGD2U0CCDIvxOKk+Hy0om1w74PpD2XJWv3vWddGBwLCz/F7gtuaIZCbohWaozW21gPvNGwCPH1oIvE+gH3GPac7/jzz2MCaAGsJZGgeFhY9YWIgET+g7QtlHeDLFlvQfNNWgnbbROHQkJg1I0P36Nbec5T6kQcMyAIaHGEBW/wNtxrdYnreT038do7LF4er8Oz9KrIf9vKNDFF7UV/yKbosff6rJZapXipleX/icjgMsNL//Gt5W2scpk02p6x3FvL1zy5Yn4GTa0=
  keep-history: true
  local-dir: public
  on:
    branch: master
