base_url = "https://rust-br.github.io/blog"

# RSS
title = "rust::br::Blog"
description = "Um blog com conteudo brasileiro sobre Rust Lang"
default_language = "pt"

theme = "dinkleberg"
compile_sass = true

highlight_code = true
highlight_theme = "solarized-dark"

generate_tags_pages = true
generate_categories_pages = true

[extra]
sidebar = [
    {name = "Social", urls=[
        {name="Telegram", url="https://t.me/rustlangbr"},
        {name="Github", url="https://github.com/rust-br"},
    ]}
]

