base_url = "localhost:8080"

# RSS
title = "Rust Brazil Blog"
description = "Um blog com conteudo brasileiro sobre Rust Lang"
default_language = "pt"

theme = "after-dark"
compile_sass = true

highlight_code = true
highlight_theme = "solarized-dark"

build_search_index = true

# [extra]
# Put all your custom variables here
