base_url = "https://rust-br.github.io/blog"

# RSS
title = "Rust Brasil: Dividindo conhecimento sobre a linguagem Rust"
description = "Um blog com conteúdo focado no público brasileiro escrito, grande parte, em português sobre a linguagem de programção Rust"
default_language = "pt"

theme = "dinkleberg"
compile_sass = true

highlight_code = true
highlight_theme = "gruvbox-dark"

generate_tags_pages = true
generate_categories_pages = true

[extra]
blog_logo = "/imgs/common/logo.png"
blog_title="rust::brasil::Blog"
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categorias"
label_category = "Categoria"
label_relative_posts = "Postagens Relacionadas"
label_next = "Próxima"
label_previous = "Anterior"
label_page = "Página"
label_of = "de"

og_image="https://rust-br.github.io/blog/imgs/common/base_og_image.png"
og_alt_image="Rust Brasil Blog"
og_site_name="Rust Brasil Blog"
keywords="Rust, Lang, Language, Linguagem de Programação, Desenvolvimento, Brazil, Brasil"

educational_use="knowledge share"
copyright_year="2018"

sidebar = [
    {name = "Social", urls=[
        {name="Telegram", url="https://t.me/rustlangbr"},
        {name="Github", url="https://github.com/rust-br"},
    ]},
    {name = "Divida Conhecimento!", urls=[
        {name="Contribuir!", url="https://rust-br.github.io/blog/hello-world"}
    ]}
]
